In [1]:
#Allowable Library
import numpy as np
import scipy as sc
import pandas as pd

In [2]:
train = pd.read_csv("train.csv", encoding="big5")
train

日期  測站          測項     0     1     2     3     4     5     6  \
0       2014/1/1  大里    AMB_TEMP    14    13    13    12    12    12    12   
1       2014/1/1  大里         CH4   1.9   1.9   2.1   2.1   2.2   2.2   2.2   
2       2014/1/1  大里          CO  1.16     1  1.09  1.18  1.01     1  1.15   
3       2014/1/1  大里        NMHC   0.7  0.59  0.66  0.65  0.52   0.5  0.58   
4       2014/1/1  大里          NO    17   8.8    14    33    26    21    34   
5       2014/1/1  大里         NO2    31    29    26    25    23    21    20   
6       2014/1/1  大里         NOx    47    38    41    57    49    41    54   
7       2014/1/1  大里          O3   2.4     3   2.6   2.3   2.1   2.3   2.5   
8       2014/1/1  大里        PM10    91   104    87    91    83    76    73   
9       2014/1/1  大里       PM2.5    58    59    57    59    64    64    60   
10      2014/1/1  大里    RAINFALL    NR    NR    NR    NR    NR    NR    NR   
11      2014/1/1  大里          RH    79    79    80    83    83    83    82   
12      2014/1/1  大里         SO2   3.4   3.6   2.7   2.9   2.9   2.4   2.7   
13      2014/1/1  大里         THC   2.6   2.5   2.8   2.8   2.7   2.8   2.8   
14      2014/1/1  大里       WD_HR   146   110   183   234   178   143   247   
15      2014/1/1  大里  WIND_DIREC   133   136   248   187   163    22   257   
16      2014/1/1  大里  WIND_SPEED     1   0.5     1   0.5   0.5   0.5   1.1   
17      2014/1/1  大里       WS_HR   0.7   0.8   0.5   0.5   0.5   0.3   0.4   
18      2014/1/2  大里    AMB_TEMP    16    16    16    15    15    14    14   
19      2014/1/2  大里         CH4     2   2.2   1.9   1.8   1.8     2   1.9   
20      2014/1/2  大里          CO  0.96  1.05  0.72  0.45  0.41   0.5  0.61   
21      2014/1/2  大里        NMHC   0.5  0.59  0.44  0.31  0.24  0.27  0.26   
22      2014/1/2  大里          NO   2.4   8.2     4   1.6   1.4   2.5   6.4   
23      2014/1/2  大里         NO2    34    33    26    13    12    17    22   
24      2014/1/2  大里         NOx    37    41    30    14    13    19    29   
25      2014/1/2  大里          O3   3.3   2.6   8.5    15    17   8.6     4   
26      2014/1/2  大里        PM10    72    71    77    54    43    40    40   
27      2014/1/2  大里       PM2.5    41    45    48    43    19     9    10   
28      2014/1/2  大里    RAINFALL    NR    NR    NR    NR    NR    NR    NR   
29      2014/1/2  大里          RH    73    74    75    76    76    80    80   
...          ...  ..         ...   ...   ...   ...   ...   ...   ...   ...   
4290  2014/12/19  大里         NOx    53    54    29    31    37    42    56   
4291  2014/12/19  大里          O3   4.2   3.9   5.1   5.2   3.5   3.8   3.8   
4292  2014/12/19  大里        PM10    75    77    66    56    46    43    47   
4293  2014/12/19  大里       PM2.5    42    35    35    34    40    41    42   
4294  2014/12/19  大里    RAINFALL    NR    NR    NR    NR    NR    NR    NR   
4295  2014/12/19  大里          RH    69    71    71    71    75    74    73   
4296  2014/12/19  大里         SO2   2.9   2.8   2.4   2.4   1.7   2.2   3.3   
4297  2014/12/19  大里         THC   2.6   2.7   2.6   2.5   2.6   2.6   2.8   
4298  2014/12/19  大里       WD_HR   198   260    77   299   240   155   290   
4299  2014/12/19  大里  WIND_DIREC   247    83    37   234   287    35   264   
4300  2014/12/19  大里  WIND_SPEED   0.7   0.7   0.8   0.6   0.6   0.6   0.7   
4301  2014/12/19  大里       WS_HR   0.6   0.2   0.8   0.1   0.7   0.3   0.2   
4302  2014/12/20  大里    AMB_TEMP    14    14    14    14    15    15    15   
4303  2014/12/20  大里         CH4   1.8   1.8   1.8   1.8   1.7   1.7   1.7   
4304  2014/12/20  大里          CO  0.59  0.61  0.35  0.23  0.19  0.17  0.25   
4305  2014/12/20  大里        NMHC  0.37  0.38  0.14  0.09  0.06  0.04  0.08   
4306  2014/12/20  大里          NO   3.6   5.6   1.5     1     1   0.9   1.1   
4307  2014/12/20  大里         NO2    23    27    18    11   8.9   7.8    11   
4308  2014/12/20  大里         NOx    27    32    20    12    10   8.7    12   
4309  2014/12/20  大里          O3   5

In [3]:
filter1 = train["測項"]=="PM2.5"
pm25_train = train[filter1]
pm25_train.drop(['日期', '測站', '測項'], axis = 1, inplace=True)
pm25_train

/home/jun-han-chen/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


0    1   2   3   4   5   6   7   8   9 ...   14  15  16  17  18  19  \
9      58   59  57  59  64  64  60  55  54  61 ...   36  38  40  42  46  57   
27     41   45  48  43  19   9  10  14  20  33 ...   48  44  38  34  40  54   
45     82   69  62  55  66  63  48  24  14  18 ...   44  38  38  35  38  38   
63     53   55  51  45  43  44  43  39  32  35 ...   73  71  65  65  70  82   
81    107  103  93  83  77  74  69  65  66  75 ...   75  72  68  65  63  70   
99     75   70  68  67  65  60  58  65  71  82 ...   90  98  86  65  44  43   
117    65   58  49  51  45  46  38  39  36  47 ...   55  57  54  54  53  58   
135    56   51  54  52  54  53  60  65  74  72 ...   33  36  35  45  45  42   
153    24   23  15  12   8  14  14  20  22  25 ...   17  22  21  15   8  13   
171     3    2   4   8  14  15   7   4   3   9 ...   32  30  24  16  14  22   
189    24   28  30  22  21  17  22  22  32  35 ...   54  44  36  36  41  36   
207    39   45  48  60  65  67  67  54  41  34 ...   24  26  24  20  22  22   
225    18   16  11  11  14  17  20  11  13  13 ...   25  33  34  37  32  34   
243    41   44  46  34  21  17  22  30  32  31 ...   16  21  14  14  14  18   
261    11   10  11  10  10  14  15  20  18  18 ...   24  23  23  20  19  31   
279    34   39  31  31  23  24  27  32  34  34 ...   19  22  30  37  34  33   
297    50   45  44  41  38  34  32  27  25  36 ...   31  31  32  31  27  27   
315    32   30  24  20  12  11  11  17  20  18 ...   46  70  87  92  94  99   
333    80   76  67  72  70  75  77  78  85  81 ...   56  63  63  67  80  85   
351   104   95  88  81  78  75  72  60  50   0 ...   58  43  37  30  39  44   
369    59   54  46  41  33  32  27  26  34  43 ...   14  10  16  26  26  25   
387    31   31  31  28  28  23  24  20  23  23 ...    9  12  14  21  21  20   
405    42   44  37  36  33  40  32  27  22  25 ...   34  24  20  19  24  19   
423    36   34  30  31  34  35  34  26  21  13 ...   23  21  17  21  16  16   
441    13   14  11  11  10   5  11   5  10   9 ...   34  35  30  24  25  25   
459    25   27  24  27  28  29  20   9   4   8 ...   44  46  45  43  44  38   
477    50   55  45  43  35  37  38  34  30  27 ...   29  32  34  34  34  28   
495    35   48  49  43  29  21  18  15  14   5 ...   10  17  15  20  24  24   
513    18   16  20  14   9   4   5  10   5   8 ...   10   6  14   8   9   9   
531     7    5   1  -1   1   1   3   2   4   3 ...    5  12  15  16  19  17   
...   ...  ...  ..  ..  ..  ..  ..  ..  ..  .. ...   ..  ..  ..  ..  ..  ..   
3789   25   24  23  22  21  20  25  35  44  45 ...   60  45  41  34  40  35   
3807   55   47  42  32  33  38  42  38  24  23 ...   21  22  26  24  31  24   
3825   21   24  21  26  30  33  33  29  39  34 ...   24  29  24  37  38  41   
3843   19   16  17  19  16  18  19  31  30  35 ...   40  53  52  42  25  17   
3861   19   20  19  21  23  22  18  16  17  21 ...   33  30  32  45  54  59   
3879   58   46  43  35  24  10  14   8  14  20 ...   20  19  15  17  14  19   
3897   10   15  13  20   7  12   3   6   7   7 ...    5  11  -3  22  13  12   
3915   14   18  17  12  13  12  18  21  30  25 ...   26  27  22  15  23  20   
3933   10   13   8  16  15  15  17  22  32  32 ...   67  86  82  72  46  42   
3951   35   39  34  34  29  30  28  33  41  41 ...   36   0  37  40  44  45   
3969   70   52  40  34  25  16  11  11   9   5 ...   12  16  25  34  33  31   
3987   26   21  26  22  24  28  32  31  27  30 ...   25  24  27  26  30  18   
4005   24   22  20  25  24  24  21  21  24  31 ...    0  42  44  45  53  48   
4023   34   34  33  20  12   1   1   3   5   4 ...   13  15  20  22  22  30   
4041   24   31  28  23  14  12  17  17  18  17 ...   26  32  35  42  37  32   
4059   49   52  53  48  40  35  37  36  43  31 ...   26  32  35  -3   0   0   
4077    0    0   0   0   0   0   0   0   0   0 ...   38  52  54  51  38  35   
4095   45   43  40  49  44  38  32  33  24  17 ...   14  10  14  25  43  42   
4113   31   26  27  24  14  18  18  25  17  26 ...   52  5

In [4]:
tempxlist=[]
tempylist=[]
for i in range(15):
    tempx=pm25_train.iloc[:,i:i+9]        #使用前9小时数据作为feature
    tempx.columns=np.array(range(9))
    tempy=pm25_train.iloc[:,i+9]         #使用第10个小数数据作为lable
    tempy.columns=['1']
    tempxlist.append(tempx)
    tempylist.append(tempy)

In [5]:
xdata=pd.concat(tempxlist)     #feature数据
x=np.array(xdata,float)     
x  

array([[58., 59., 57., ..., 60., 55., 54.],
       [41., 45., 48., ..., 10., 14., 20.],
       [82., 69., 62., ..., 48., 24., 14.],
       ...,
       [47., 45., 37., ..., 40., 45., 47.],
       [21., 26., 26., ..., 27., 26., 22.],
       [16., 25., 24., ..., 49., 51., 48.]])

In [6]:
x.shape

(3600, 9)

In [7]:
ydata=pd.concat(tempylist)      #lable数据
ydata.head()
y=(np.array(ydata,float))
y

array([61., 33., 18., ..., 43., 24., 49.])

In [8]:
y.shape

(3600,)

In [9]:
x = np.concatenate((np.ones((x.shape[0],1)),x), axis=1)      #在feature基础上加入bias
x

array([[ 1., 58., 59., ..., 60., 55., 54.],
       [ 1., 41., 45., ..., 10., 14., 20.],
       [ 1., 82., 69., ..., 48., 24., 14.],
       ...,
       [ 1., 47., 45., ..., 40., 45., 47.],
       [ 1., 21., 26., ..., 27., 26., 22.],
       [ 1., 16., 25., ..., 49., 51., 48.]])

In [10]:
# 初始化一个参数矩阵
w=np.zeros((len(x[0])))

#初始化一个learning rate
lr=0.1
iteration= 20000 #迭代10000次
s_grad=np.zeros(len(x[0]))
for i in range(iteration):
    tem=np.dot(x,w)     #&y^*&(预测值)
    loss=y-tem     
    grad=np.dot(x.transpose(),loss)*(-2)
    s_grad+=grad**2
    ada=np.sqrt(s_grad)
    w=w-lr*grad/ada
w    

array([ 8.14303301, -0.12197851,  0.05796001, -0.02845727,  0.11367957,
        0.26334337, -0.0409786 ,  0.0834175 , -0.10221488,  0.50835431])

In [29]:
abs(loss).mean()

8.556169915561995

In [27]:
w.shape

(10,)

In [11]:
pm25_train.to_csv("pm25_train.csv")

In [12]:
test = pd.read_csv("test.csv", encoding="big5")
test

id_0    AMB_TEMP    35  35.1  35.2    34    33    31    30    29  29.1
0       id_0         CH4   1.6   1.7   1.7   1.6   1.6   1.6   1.7   1.7   1.7
1       id_0          CO  0.17  0.15  0.14  0.14  0.17  0.22   0.3  0.37  0.42
2       id_0        NMHC  0.02  0.01  0.01  0.01  0.03  0.04  0.08  0.13  0.11
3       id_0          NO   1.6   1.7     2   2.1   1.9   1.8   1.8   1.6   1.7
4       id_0         NO2   4.4   4.7   4.6   4.5   5.6   7.6    11    12    15
5       id_0         NOx     6   6.5   6.6   6.6   7.5   9.5    13    14    17
6       id_0          O3    61    60    54    53    51    51    46    45    42
7       id_0        PM10    42    42    35    37    34    41    41    49    51
8       id_0       PM2.5    39    43    29    23    25    27    32    26    40
9       id_0    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
10      id_0          RH    50    51    51    54    58    63    66    67    65
11      id_0         SO2     3   2.9   2.4   2.4   2.1   2.6   2.9   2.8   2.9
12      id_0         THC   1.7   1.7   1.7   1.6   1.6   1.7   1.7   1.8   1.8
13      id_0       WD_HR   269   261   269   267   270   278   276   281   243
14      id_0  WIND_DIREC   260   265   276   267   278   278   278   283   220
15      id_0  WIND_SPEED     3   3.5   3.2   3.3   3.1     2   1.9   1.6   1.2
16      id_0       WS_HR   2.3   2.9   3.3   3.6     3     2     2   1.8   0.9
17      id_1    AMB_TEMP    24    25    25    27    29    29    30    30    30
18      id_1         CH4   1.7   1.7   1.6   1.6   1.6   1.6   1.6   1.6   1.6
19      id_1          CO  0.13  0.12  0.16  0.22  0.24  0.19  0.18  0.18  0.17
20      id_1        NMHC  0.03  0.02  0.04  0.05  0.11  0.11  0.13  0.08  0.05
21      id_1          NO   0.9     1   1.6   2.3     4   3.8   3.4   2.4   2.7
22      id_1         NO2     3   3.3   4.5   4.2   6.5   5.3   5.4     5   4.8
23      id_1         NOx   3.9   4.3   6.1   6.5    10     9   8.8   7.4   7.4
24      id_1          O3    23    21    18    19    20    22    25    26    30
25      id_1        PM10    25    24    19    19    25    25    28    29    28
26      id_1       PM2.5    18    13    22    18    14    10    13    11    14
27      id_1    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
28      id_1          RH    67    65    65    64    58    58    56    57    56
29      id_1         SO2   2.2   2.4   2.4   2.4   3.1   2.8   2.9   2.6   2.4
...      ...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
4649  id_258         NOx    23    22    22    22    23    31    40    32    33
4650  id_258          O3   115   113   101    78    73    50    24    18    14
4651  id_258        PM10   108   117   110    96    82    86    81    80    69
4652  id_258       PM2.5    69    71    61    55    47    43    39    32    29
4653  id_258    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
4654  id_258          RH    55    53    59    60    62    67    71    75    76
4655  id_258         SO2   3.6   4.1   4.4     3   3.8   3.5   3.3   3.9   4.2
4656  id_258         THC   2.1     2     2   1.9   2.4   2.3   2.3   2.2   2.2
4657  id_258       WD_HR   219   256   265   272   328   320   324   344     5
4658  id_258  WIND_DIREC   238   279   266   287   318   322   325   321   156
4659  id_258  WIND_SPEED   1.8   2.3   2.7     2   2.5   2.1   2.4   1.3   1.7
4660  id_258       WS_HR   1.4   1.8   2.3   2.4   1.1   1.4   1.2   0.6   0.3
4661  id_259    AMB_TEMP    21    21    21    21    21    20    20    22    24
4662  id_259         CH4   1.9   1.9     2     2     2     2     2   2.1   2.1
4663  id_259          CO  0.75  0.67  0.65  0.68  0.61  0.68  0.83  1.41  1.31
4664  id_259        NMHC  0.46  0.43   0.5  0.52  0.38  0.45  0.52  0.79   0.7
4665  id_259          NO    13    10    10   7.8   6.1    10    12    34    26
4666  id_259         NO2    33    34    34    28    23    25    27    31    39
4667  id_259         NOx    45    44    44    36    29    

In [13]:
filter2 = test["AMB_TEMP"]=="PM2.5"

pm25Test = test[filter2]

pm25Test.drop(['id_0', 'AMB_TEMP'],1,inplace=True)
pm25Test

/home/jun-han-chen/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


35 35.1 35.2  34  33  31   30   29 29.1
8      39   43   29  23  25  27   32   26   40
26     18   13   22  18  14  10   13   11   14
44     20   17   17  24  20  22   10    8    5
62     11    4    8  12  13  15   25   28   20
80     34   24   19  17  19  16   21   27   27
98    118  122  102  76  70  83  106  116  117
116    81   76   62  53  43  36   32   32   28
134    32   29   24  28  24  23   21   28   34
152    53   61   61  47  36  34   41   47   43
170    34   24   16  14  16  18   14   16   17
188    25   27   33  39  39  34   27   32   23
206    25   23   21  25  25  31   34   42   42
224    43   34   32  30  34  29   34   38   43
242    13    7   10  12  14  14   11   14   13
260    21   16   20  13  23  16   24   21   27
278    95   87   85  76  70  65   63   54   43
296    38   24   20  15  18  25   32   36   36
314    50   50   51  60  65  70   72   65   55
332    18   21   22  22  22  24   18   20   21
350    24   22   19  10   4   4    6   10   10
368     5    5    3   3   7   6   16   19   31
386    27   23   26  21  22  19   16   28   30
404    28   26   30  44  53  59   57   56   54
422    34   34   34  31  30  27   36   44   50
440     4    3    1   4   6  15   19   21   20
458    16   13   16  20  17  14    9    9   10
476    31   34   40  40  45  49   45   46   45
494    54   51   45  42  42  35   41   36   35
512    38   42   40  48  44  47   38   47   62
530     9   14   14  19  23  20   14   11   15
...   ...  ...  ...  ..  ..  ..  ...  ...  ...
4148   38   30   20   7   5  11   15   17    9
4166   39   42   34  29  24  25   29   33   33
4184   15   11    5   6   6   5    8   11    0
4202   22   24   24  23  21  21   20   24   30
4220   40   36   41  41  43  35   41   46   60
4238   46   36   34  33  27  25   20   21   21
4256   24   35   38  35  25  20   15   13   14
4274    8   14    7   9   5   9    8   10   12
4292   19   20   28  27  18  16   20   24   16
4310   29   27   22  21  22  15   15   22   33
4328   45   45   45  54  58  59   41   31   22
4346   55   56   58  61  64  68   75   77   75
4364   35   28   24  24  30  34   36   37   37
4382   47   64   68   0  63  62   42   40   29
4400   46   47   44  45  40  43   37   48   55
4418   73   75   74  75  65  65   49   45   35
4436   24   26   30  27  34  31   38   36   45
4454   41   32   34  38  46  46   38   38   44
4472    5    8   10  14  17  23   26   25   22
4490   12    6   10  15  19  19   17    9    4
4508   21    8    6   2  10  12   14   11   14
4526   38   43   40  36  33  31   34   29   36
4544   11   12   14  14  23  21   22   13   14
4562   32   26   20   8  15  22   31   28   28
4580   13   14   19  24  21  19   25   25   21
4598    9   14   14  14   9  12   20   30   34
4616   39   45   43  45  33  38   40   43   40
4634    1    3    6   3   5   1    6    1    6
4652   69   71   61  55  47  43   39   32   29
4670   27   24   25  28  24  29   27   35   39

[260 rows x 9 columns]

In [14]:
pm25Test.to_csv("pm25Test.csv")

In [15]:
x_test=np.array(pm25Test,float)
x_test

array([[39., 43., 29., ..., 32., 26., 40.],
       [18., 13., 22., ..., 13., 11., 14.],
       [20., 17., 17., ..., 10.,  8.,  5.],
       ...,
       [ 1.,  3.,  6., ...,  6.,  1.,  6.],
       [69., 71., 61., ..., 39., 32., 29.],
       [27., 24., 25., ..., 27., 35., 39.]])

In [26]:
x_test_b=np.concatenate((np.ones((x_test.shape[0],1)),x_test),axis=1)
x_test

array([[39., 43., 29., ..., 32., 26., 40.],
       [18., 13., 22., ..., 13., 11., 14.],
       [20., 17., 17., ..., 10.,  8.,  5.],
       ...,
       [ 1.,  3.,  6., ...,  6.,  1.,  6.],
       [69., 71., 61., ..., 39., 32., 29.],
       [27., 24., 25., ..., 27., 35., 39.]])

In [17]:
y_star=np.dot(x_test_b,w)
y_star

array([33.49062856, 18.47511767, 15.85688486, 20.36889797, 23.8440671 ,
       78.0532914 , 30.40934112, 29.97214499, 37.38312146, 18.17331099,
       29.70356842, 33.87833576, 35.94491206, 17.25091159, 26.39984735,
       45.18373643, 27.04103321, 51.8819585 , 23.98219633, 12.53813501,
       24.82772025, 26.56832884, 48.40413616, 39.24009322, 18.8261474 ,
       17.58063568, 41.51157881, 35.16507222, 49.80534556, 22.52429815,
       22.42917982, 34.45824676, 33.17502387, 23.60068204, 51.7918828 ,
       36.34101488, 18.85678228, 40.29972897, 26.88268523,  9.93405752,
       26.9952806 , 12.1676417 , 44.04015898, 30.96412754, 37.30563577,
       35.82490619, 36.14686362, 23.53993433, 27.01680467, 46.56678168,
       24.6224551 , 46.84595028, 29.51965754, 28.49930981, 20.13188377,
       29.24679267, 35.7054716 , 27.00717074, 31.52944677, 12.55097977,
       57.04964196, 72.63665867, 30.80739818, 20.51141679, 19.75637337,
       32.69151428, 34.50802189, 21.63299778, 43.20995335, 13.94

In [18]:
y_star.shape

(260,)

In [19]:
sample_submission = pd.read_csv("sampleSubmission .csv", encoding="big5")
sample_submission

id  value
0      id_0      0
1      id_1      0
2      id_2      0
3      id_3      0
4      id_4      0
5      id_5      0
6      id_6      0
7      id_7      0
8      id_8      0
9      id_9      0
10    id_10      0
11    id_11      0
12    id_12      0
13    id_13      0
14    id_14      0
15    id_15      0
16    id_16      0
17    id_17      0
18    id_18      0
19    id_19      0
20    id_20      0
21    id_21      0
22    id_22      0
23    id_23      0
24    id_24      0
25    id_25      0
26    id_26      0
27    id_27      0
28    id_28      0
29    id_29      0
..      ...    ...
230  id_230      0
231  id_231      0
232  id_232      0
233  id_233      0
234  id_234      0
235  id_235      0
236  id_236      0
237  id_237      0
238  id_238      0
239  id_239      0
240  id_240      0
241  id_241      0
242  id_242      0
243  id_243      0
244  id_244      0
245  id_245      0
246  id_246      0
247  id_247      0
248  id_248      0
249  id_249      0
250  id_250      0
251  id_251      0
252  id_252      0
253  id_253      0
254  id_254      0
255  id_255      0
256  id_256      0
257  id_257      0
258  id_258      0
259  id_259      0

[260 rows x 2 columns]

In [20]:
y_pre = sample_submission

In [21]:
y_pre.value=y_star

In [22]:
y_pre

id      value
0      id_0  33.490629
1      id_1  18.475118
2      id_2  15.856885
3      id_3  20.368898
4      id_4  23.844067
5      id_5  78.053291
6      id_6  30.409341
7      id_7  29.972145
8      id_8  37.383121
9      id_9  18.173311
10    id_10  29.703568
11    id_11  33.878336
12    id_12  35.944912
13    id_13  17.250912
14    id_14  26.399847
15    id_15  45.183736
16    id_16  27.041033
17    id_17  51.881959
18    id_18  23.982196
19    id_19  12.538135
20    id_20  24.827720
21    id_21  26.568329
22    id_22  48.404136
23    id_23  39.240093
24    id_24  18.826147
25    id_25  17.580636
26    id_26  41.511579
27    id_27  35.165072
28    id_28  49.805346
29    id_29  22.524298
..      ...        ...
230  id_230  10.428012
231  id_231  29.266837
232  id_232   8.408850
233  id_233  27.917684
234  id_234  47.953573
235  id_235  23.685545
236  id_236  22.945000
237  id_237  15.495913
238  id_238  20.690571
239  id_239  28.888890
240  id_240  34.411749
241  id_241  60.543679
242  id_242  32.079218
243  id_243  32.391564
244  id_244  44.030878
245  id_245  41.739631
246  id_246  38.987551
247  id_247  40.230980
248  id_248  23.635369
249  id_249  15.204183
250  id_250  15.403912
251  id_251  34.547017
252  id_252  21.509601
253  id_253  23.093440
254  id_254  24.513497
255  id_255  26.814076
256  id_256  36.294767
257  id_257  13.089384
258  id_258  33.697900
259  id_259  32.344681

[260 rows x 2 columns]

In [23]:
y_pre.to_csv('ans2.csv', index = False)

In [24]:
real=pd.read_csv('ans.csv')
y_pre.value

0      33.490629
1      18.475118
2      15.856885
3      20.368898
4      23.844067
5      78.053291
6      30.409341
7      29.972145
8      37.383121
9      18.173311
10     29.703568
11     33.878336
12     35.944912
13     17.250912
14     26.399847
15     45.183736
16     27.041033
17     51.881959
18     23.982196
19     12.538135
20     24.827720
21     26.568329
22     48.404136
23     39.240093
24     18.826147
25     17.580636
26     41.511579
27     35.165072
28     49.805346
29     22.524298
         ...    
230    10.428012
231    29.266837
232     8.408850
233    27.917684
234    47.953573
235    23.685545
236    22.945000
237    15.495913
238    20.690571
239    28.888890
240    34.411749
241    60.543679
242    32.079218
243    32.391564
244    44.030878
245    41.739631
246    38.987551
247    40.230980
248    23.635369
249    15.204183
250    15.403912
251    34.547017
252    21.509601
253    23.093440
254    24.513497
255    26.814076
256    36.294767
257    13.0893

In [25]:
erro=abs(y_pre.value-real.value).sum()/len(real.value)
erro

0.00033565355036912364